/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jrpractice1.app;

import jrpractice1.list.LinkedList;

import static jrpractice1.utilities.StringUtils.join;
import static jrpractice1.utilities.StringUtils.split;
import static jrpractice1.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {

    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));

    }
}
